### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by shanduur** [redcode-labs/Coldfire#10]
TODO:
- [ ] error propagation
- [x] logging errors
- [x] documentation string over exported functions
- [x] documentation string on package

As listed in the TODO list above, some of the parts of code are inconsistent. 
1. You should consider using tools like `go vet`, `go fmt` and `go imports`. 
2. Unexported methods should be used.
3. Exported methods should contain [doc comment](https://blog.golang.org/godoc).
4. If this is module/library/framework, then you shouldn't log inside the functions, but return errors with additional info.
5. If some part of code should run, and fail if error occurs, name function according to the scheme `MustDoSomethin()` and then `panic` on error. Note that in doc comment.

**Comment by wintrmvte** [comment]
Everything done except error propagation - errors are handled by `Check()` because `panic()` is not informative enough
