### ISSUE TITLE
Unable to install via go get

### ISSUE THREAD

**Issue by ZephrFish** [redcode-labs/Coldfire#18]
Each time I attempt to go get -u the package I get the following error:

```
 go get -u github.com/redcode-labs/Coldfire                                                                                                                                                                 
package github.com/minio/minio/pkg/disk: cannot find package "github.com/minio/minio/pkg/disk" in any of:
	/usr/local/Cellar/go/1.14.5/libexec/src/github.com/minio/minio/pkg/disk (from $GOROOT)
	/Users/zephr/go/src/github.com/minio/minio/pkg/disk (from $GOPATH)

```

Any suggestions on how to remediate?

Version of Go: go version go1.14.5 darwin/amd64

**Comment by wintrmvte** [comment]
Hi, thanks for reaching out :> 
Please try running `sudo go get -u github.com/minio/minio/pkg/disk`.
If this malfunction persists, I will attempt to change the broken `disk` dependency to something less error-prone.

**Comment by ZephrFish** [comment]
Hey, tried that but still get an issue:
```
cannot find package "github.com/minio/minio/pkg/disk" in any of:
        /usr/lib/go-1.15/src/github.com/minio/minio/pkg/disk (from $GOROOT)
        /root/go/src/github.com/minio/minio/pkg/disk (from $GOPATH)
```

**Comment by TormentedSoul666** [comment]
go mod tidy
go mod vendor
go mod download

**Comment by unrooted** [comment]
Hi, this should be fixed by now (tested by all of us in our org, works fine for us all in here)
