### ISSUE TITLE
Usage example.

### ISSUE THREAD

**Issue by ddavies1972** [redcode-labs/Coldfire#2]
Hi

Can you please provide usage example for those of us that are new at golang.

This is what I have:

`package main

import "github.com/redcode-labs/ColdFire"

func main() {
  coldfire.print_good("this is a test")
}`

The result is this:
./main.go:6:3: cannot refer to unexported name coldfire.print_good
./main.go:6:3: undefined: coldfire.print_good

Thanks for your time!

**Comment by wintrmvte** [comment]
Hi, thank you for your input. Apparently, I forgot that `underscore_named` functions are non-exportable. Will fix those names with Camel soon. For now, only changed the symbols required by [Neurax](https://github.com/redcode-labs/Neurax).

**Comment by wintrmvte** [comment]
Done, I will reopen if something was omitted.
