### ISSUE TITLE
Bruteforce/Spreading features?

### ISSUE THREAD

**Issue by TormentedSoul666** [redcode-labs/Coldfire#21]
Hey, awesome work! Do you plan on bruteforce and additional spreading features?

**Comment by wintrmvte** [comment]
Hi, Im glad you like it :>
Those features are already present in our other project - Neurax. Check it out ;>

**Comment by TormentedSoul666** [comment]
Hehe, already found Neurax listed on kitploit but iirc it can only replicate in the local network and not over WAN?

**Comment by unrooted** [comment]
@TormentedSoul666 It can replicate over WAN as well.

Sorry for the late reply, I forgot about this issue lmfao

Tho feel free to contribute to all of our open source solutions
