### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [redcode-labs/Coldfire#34]
It would be very helpful if you could tag a release. This would enable distributions to fetch the source from GitHub instead of working with checkouts. Easier to track for package maintainer, too.

Thanks

**Comment by fendi1989** [comment]
hello fabaff i'm getting those erros please, any help??

go get github.com/redcode-labs/Coldfire: invalid github.com import path "github.com/redcode-labs"

imports github.com/redcode-labs/Coldfire
imports github.com/redcode-labs/Coldfire: import cycle not allowed


Nobody's answering here, thx in advance.

**Comment by unrooted** [comment]
Hi, also missed this one, here you go: https://github.com/redcode-labs/Coldfire/releases/tag/2.0
